apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - common/configuration.yaml

generatorOptions:
  disableNameSuffixHash: true

labels:
  - includeTemplates: true
    includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: entra-oidc-demo

resources:
  - entra-oidc-demo/
  - common/service-account.yaml
